# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Turfy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Turfy
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  target 'TurfyTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
  end

  target 'TurfyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
